---
services:
  app:
    image: szeu-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    ports:
      - "${APP_EXTERNAL_PORT:-8080}:80"
      - "${XDEBUG_EXTERNAL_PORT:-9003}:9003"
      - "5173:5173" # This is for vite, it is not configurable, only together with vite.config.js
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
    networks:
      - szeu-network
    depends_on:
      database:
        condition: service_healthy
      # migrator:
      #   condition: service_completed_successfully
  database:
    image: pgvector/pgvector:pg17
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - szeu-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tmp:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homestead -d bible"]
      start_period: 1m
      interval: 10s
      timeout: 5s
      retries: 3      
  # mailpit:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  # composer:
  #   image: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - .:/var/www/html
  #   command: php composer.phar install
  # migrator:
  #   image: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - .:/var/www/html
  #   command: php artisan migrate -n
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #     composer:
  #       condition: service_completed_successfully
volumes:
  db-data:
networks:
  szeu-network:
